# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20190222_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAvail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('food_type', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
