# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-23 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantlocation_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamps',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
