# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20190223_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='my_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
