# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-23 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_restaurantlocation_my_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocation',
            old_name='timestamps',
            new_name='timestamp',
        ),
    ]
